# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import store_pb2 as proto_dot_store__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StoreServiceStub:
    """==========================================
    Definición del Servicio StoreService
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrder = channel.unary_unary(
                '/store.StoreService/CreateOrder',
                request_serializer=proto_dot_store__pb2.OrderRequest.SerializeToString,
                response_deserializer=proto_dot_store__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.StreamOrderUpdates = channel.unary_stream(
                '/store.StoreService/StreamOrderUpdates',
                request_serializer=proto_dot_store__pb2.OrderId.SerializeToString,
                response_deserializer=proto_dot_store__pb2.OrderStatus.FromString,
                _registered_method=True)


class StoreServiceServicer:
    """==========================================
    Definición del Servicio StoreService
    ==========================================
    """

    def CreateOrder(self, request, context):
        """Método Unary: recibe los datos de la orden y retorna la confirmación
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOrderUpdates(self, request, context):
        """Método Server-Streaming: recibe un OrderId y transmite una secuencia continua de cambios de estado
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=proto_dot_store__pb2.OrderRequest.FromString,
                    response_serializer=proto_dot_store__pb2.OrderResponse.SerializeToString,
            ),
            'StreamOrderUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOrderUpdates,
                    request_deserializer=proto_dot_store__pb2.OrderId.FromString,
                    response_serializer=proto_dot_store__pb2.OrderStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'store.StoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('store.StoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StoreService:
    """==========================================
    Definición del Servicio StoreService
    ==========================================
    """

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/store.StoreService/CreateOrder',
            proto_dot_store__pb2.OrderRequest.SerializeToString,
            proto_dot_store__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOrderUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/store.StoreService/StreamOrderUpdates',
            proto_dot_store__pb2.OrderId.SerializeToString,
            proto_dot_store__pb2.OrderStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
