# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/store.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/store.proto\x12\x05store\"W\n\x0cOrderRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x11\n\titem_name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x01\"U\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"\x1b\n\x07OrderId\x12\x10\n\x08order_id\x18\x01 \x01(\t\"R\n\x0bOrderStatus\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t2\x84\x01\n\x0cStoreService\x12\x38\n\x0b\x43reateOrder\x12\x13.store.OrderRequest\x1a\x14.store.OrderResponse\x12:\n\x12StreamOrderUpdates\x12\x0e.store.OrderId\x1a\x12.store.OrderStatus0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=28
  _globals['_ORDERREQUEST']._serialized_end=115
  _globals['_ORDERRESPONSE']._serialized_start=117
  _globals['_ORDERRESPONSE']._serialized_end=202
  _globals['_ORDERID']._serialized_start=204
  _globals['_ORDERID']._serialized_end=231
  _globals['_ORDERSTATUS']._serialized_start=233
  _globals['_ORDERSTATUS']._serialized_end=315
  _globals['_STORESERVICE']._serialized_start=318
  _globals['_STORESERVICE']._serialized_end=450
# @@protoc_insertion_point(module_scope)
